language: ruby
notifications:
  email:
    recipients:
      - noel@peden.biz
    on_success: always
env:
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.0
  - RAILS_VERSION=4.1
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script:
  test/ci.sh
